# Generated by Django 3.0.5 on 2020-04-16 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
