# Generated by Django 3.0.5 on 2020-04-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0003_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
