# Generated by Django 3.0.5 on 2020-04-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0004_auto_20200416_1129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageModel',
        ),
    ]
