# Generated by Django 3.0.5 on 2020-04-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_app', '0005_auto_20200416_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
